version: "3"
services:
  mysql:                       
    container_name: mysql_container
    restart: always
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: myDb
      MYSQL_USER: user 
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: devved
    
    ports:
      - "8889:3306"
  
         #why does binding not work??
  app:                            #initialisiert bei build (app directory)
    container_name: node    # Bei build initialisierter container_name (Zufällig)
    restart: always               # restart container on service startup?
    build: .                      # build container from .
    ports:
      - "8887:8887"               # expose default node port
    depends_on:
      - "mysql"
    command: ["./wait/wait-for-it.sh", "mysql:3306","-t", "30" , "--" , "npm" , "start" ]  
    links:
      - mysql                # provide network access to `mysql_container`



   
    
